Use python 3.12 again

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Setup python
         uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
         with:
-          python-version: '3.13'
+          python-version: '3.12'
           cache: 'pip'
       - name: Run linter for pyspec
         run: |
@@ -34,25 +34,6 @@ jobs:
         run: |
           if git grep -n '[[:blank:]]$'; then
             echo "Trailing whitespace found. Please fix it."
-            exit 1
-          fi
-
-  modcheck:
-    runs-on: [self-hosted-ghr-custom, size-s-x64, profile-consensusSpecs]
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - name: Setup python
-        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
-        with:
-          python-version: '3.13'
-          cache: 'pip'
-      - name: Run generators with --modcheck
-        run: make gen_all modcheck=true 2>&1 | tee consensustestgen.log
-      - name: Check for errors
-        run: |
-          if grep -q "\[ERROR\]" consensustestgen.log; then
-            echo "There is an error in the log"
             exit 1
           fi
 
@@ -77,7 +58,27 @@ jobs:
       - name: Setup python
         uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
         with:
-          python-version: '3.13'
+          python-version: '3.12'
           cache: 'pip'
       - name: Run pyspec tests for ${{ matrix.fork }}
         run: make test preset=minimal fork=${{ matrix.fork }}
+
+  modcheck:
+    needs: [lint, whitespace]
+    runs-on: [self-hosted-ghr-custom, size-s-x64, profile-consensusSpecs]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: Setup python
+        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
+        with:
+          python-version: '3.12'
+          cache: 'pip'
+      - name: Run generators with --modcheck
+        run: make gen_all modcheck=true 2>&1 | tee consensustestgen.log
+      - name: Check for errors
+        run: |
+          if grep -q "\[ERROR\]" consensustestgen.log; then
+            echo "There is an error in the log"
+            exit 1
+          fi
